DATABASE_TYPE: "postgres"
DATABASE_HOST: "61.28.227.243"
DATABASE_PORT: "5432"
DATABASE_USERNAME: "admin"
DATABASE_PASSWORD: "adminpw"
DATABASE_NAME: "policy-system"
DATABASE_URI: "postgresql://admin:adminpw@61.28.227.243:5432/test"
# DATABASE_URI: "sqlite://"
